[package]
name = "bevy-inspector-egui"
version = "0.3.0"
authors = [
    "Jakob Hellermann <jakob.hellermann@protonmail.com>",
    "Will Crichton <wcrichto@cs.stanford.edu>",
]
edition = "2018"
repository = "https://github.com/jakobhellermann/bevy-inspector-egui/"
readme = "README.md"
license = "MIT"
description = "Inspector plugin for the bevy game engine"
keywords = ["bevy", "inspector", "visual", "editor", "game"]
categories = ["development-tools::procedural-macro-helpers", "game-development", "gui", "visualization"]
exclude = ["docs/*"]

[features]
rapier = ["bevy_rapier3d"]

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", default-features = false }
bevy_egui = { git = "https://github.com/jakobhellermann/bevy_egui", branch = "bevy-0.5", default-features = false }
bevy_rapier3d = { git = "https://github.com/alec-deason/bevy_rapier", branch = "tracking_changes_for_bevy_0.5", optional = true }
pretty-type-name = "1.0"

bevy-inspector-egui-derive = { path = "bevy-inspector-egui-derive" }

[dev-dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", default-features = false, features = ["x11", "render", "bevy_wgpu", "bevy_winit", "dynamic"] }
bevy_mod_picking = { git = "https://github.com/aevyrie/bevy_mod_picking/" }
noise = "0.7"

[[example]]
name = "all_features"
required-features = ["nightly"]

[[example]]
name = "rapier"
required-features = ["rapier"]

[[example]]
name = "texture"
required-features = ["bevy/png"]
