[package]
name = "bevy-inspector-egui"
version = "0.3.0"
authors = [
    "Jakob Hellermann <jakob.hellermann@protonmail.com>",
    "Will Crichton <wcrichto@cs.stanford.edu>",
]
edition = "2018"
repository = "https://github.com/jakobhellermann/bevy-inspector-egui/"
readme = "README.md"
license = "MIT"
description = "Inspector plugin for the bevy game engine"
keywords = ["bevy", "inspector", "visual", "editor", "game"]
categories = ["development-tools::procedural-macro-helpers", "game-development", "gui", "visualization"]
exclude = ["docs/*"]


[features]
nightly = []
rapier = ["bevy_rapier3d"]

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", default-features = false }
bevy_egui = { git = "https://github.com/jakobhellermann/bevy_egui", branch = "bevy-0.5", default-features = false }
bevy_rapier3d = { git = "https://github.com/jakobhellermann/bevy_rapier", branch = "bevy-0.5", optional = true }

bevy-inspector-egui-derive = { path = "bevy-inspector-egui-derive" }
# bevy-inspector-egui-derive = "0.3"

[dev-dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", default-features = false, features = ["x11", "render", "bevy_wgpu", "bevy_winit"] }
bevy_rapier3d = { git = "https://github.com/jakobhellermann/bevy_rapier", branch = "bevy-0.5" }

[[example]]
name = "all_features"
required-features = ["nightly"]

[[example]]
name = "rapier"
required-features = ["rapier"]

[[example]]
name = "with_context"
required-features = ["bevy/png"]