[package]
name = "bevy-inspector-egui"
version = "0.3.0"
authors = [
    "Jakob Hellermann <jakob.hellermann@protonmail.com>",
    "Will Crichton <wcrichto@cs.stanford.edu>",
]
edition = "2018"
repository = "https://github.com/jakobhellermann/bevy-inspector-egui/"
readme = "README.md"
license = "MIT"
description = "Inspector plugin for the bevy game engine"
keywords = ["bevy", "inspector", "visual", "editor", "game"]
categories = ["development-tools::procedural-macro-helpers", "game-development", "gui", "visualization"]
exclude = ["docs/*"]
resolver = "2"

[features]
rapier = ["bevy_rapier3d"]
nightly = []

[dependencies]
bevy = { version = "0.5", default-features = false }
bevy_egui = "0.4"
emath = "0.11"
bevy_rapier3d = { version = "0.9", optional = true }
pretty-type-name = "1.0"
image = "0.23"

bevy-inspector-egui-derive = { path = "bevy-inspector-egui-derive" }

[dev-dependencies]
bevy = { version = "0.5", default-features = false, features = ["x11", "render", "bevy_wgpu", "bevy_winit", "dynamic"] }
bevy_mod_picking = { version = "0.4" }
noise = "0.7"

[[example]]
name = "rapier"
required-features = ["rapier"]

[[example]]
name = "texture"
required-features = ["bevy/png"]
