[package]
name = "bevy-inspector-egui"
version = "0.1.0"
authors = ["Jakob Hellermann <jakob.hellermann@protonmail.com>"]
edition = "2018"
repository = "https://github.com/jakobhellermann/bevy-inspector-egui/"
readme = "README.md"
license = "MIT"
description = "Inspector plugin for the bevy game engine"
keywords = ["bevy", "inspector", "visual", "editor", "game"]
categories = ["development-tools::procedural-macro-helpers", "game-development", "gui", "visualization"]


[features]
nightly = []

[dependencies]
bevy = { version = "0.4", default-features = false }
bevy_egui = "0.1"

bevy-inspector-egui-derive = { path = "bevy-inspector-egui-derive" }

[dev-dependencies]
bevy = { version = "0.4", default-features = false, features = ["x11", "render", "bevy_wgpu", "bevy_winit"] }

[[example]]
name = "all_features"
required-features = ["nightly"]