[package]
name = "bevy-inspector-egui"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/jakobhellermann/bevy-inspector-egui/"
readme = "../../README.md"
license = "MIT OR Apache-2.0"
description = "Inspector plugin for the bevy game engine"
keywords = ["bevy", "inspector", "egui", "visual", "editor", "game", "reflect"]
categories = ["game-development", "gui", "visualization", "development-tools::procedural-macro-helpers"]

[dependencies]
bevy-inspector-egui-derive = { path = "../bevy-inspector-egui-derive" }
bevy_reflect = { git = "https://github.com/bevyengine/bevy" }
bevy_ecs = { git = "https://github.com/bevyengine/bevy" }
bevy_app = { git = "https://github.com/bevyengine/bevy" }
bevy_asset = { git = "https://github.com/bevyengine/bevy" }
bevy_hierarchy = { git = "https://github.com/bevyengine/bevy" }
bevy_core = { git = "https://github.com/bevyengine/bevy" }
bevy_render = { git = "https://github.com/bevyengine/bevy" }
bevy_pbr = { git = "https://github.com/bevyengine/bevy" }
bevy_math = { git = "https://github.com/bevyengine/bevy" }
egui = "0.19.0"
pretty-type-name = "1.0.0"
smallvec = "1.9.0"
bevy_egui = { git = "https://github.com/jakobhellermann/bevy_egui", branch = "bevy-main" }
image = { version = "0.24.3", default-features = false }
once_cell = "1.14.0"

[dev-dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", default-features = false, features = ["render", "x11", "bevy_winit", "animation", "png"] }
bevy_egui = { git = "https://github.com/jakobhellermann/bevy_egui", branch = "bevy-main" }
egui_dock = { git = "https://github.com/Adanos020/egui_dock", rev = "10ade79285eb3e5303c61bdf100e8425e3fd7a1f" }
